### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by elwayman02** [dollarshaveclub/ember-router-scroll#103]
There are a lot of new features/bugfixes (like FastBoot compatibility) in this addon since the last release in Nov 2017. Can we cut a new release so that people trying this addon for the first time don't get a broken experience because they're not on master?

**Comment by rwwagner90** [comment]
@elwayman02 I'd love to, but I do not have permissions on npm. @briangonzalez any chance I could get those permissions to publish?

**Comment by yowainwright** [comment]
@elwayman02 looks like @briangonzalez published it for you. 💪

**Comment by rwwagner90** [comment]
@yowainwright I do not think it has been published. The last publish on npm was two months ago. We also are mismatched in versions. GitHub's latest is 0.4.0 and npm has 0.5.0, so the tag must not have been pushed to GitHub. We should get the tag pushed and also release a new 0.6.0 to pull in the latest changes.

**Comment by yowainwright** [comment]
NPM is update to date, as of yesterday at `0.5.0`.
```sh
npm show ember-router-scroll@* version
ember-router-scroll@0.0.1 '0.0.1'
ember-router-scroll@0.0.2 '0.0.2'
ember-router-scroll@0.0.5 '0.0.5'
ember-router-scroll@0.0.6 '0.0.6'
ember-router-scroll@0.1.0 '0.1.0'
ember-router-scroll@0.1.1 '0.1.1'
ember-router-scroll@0.2.0 '0.2.0'
ember-router-scroll@0.3.0 '0.3.0'
ember-router-scroll@0.3.1 '0.3.1'
ember-router-scroll@0.4.0 '0.4.0'
ember-router-scroll@0.5.0 '0.5.0'
```
- https://www.npmjs.com/package/ember-router-scroll

- I did not publish 0.6.0 b/c it was merged last night. I will do that today. 

In regards to git tags, @rwwagner90 as a contributor, don't you have the ability to do/automate that?

I can do that today if not.

**Comment by rwwagner90** [comment]
0.5.0 was 2 months old though. We were saying we needed a new release, i.e. 0.6.0 to be released with all the new stuff.

**Comment by yowainwright** [comment]
Thanks for clarifying @rwwagner90. 

It seems like this repo needs a CONTRIBUTING.md and GH PULL_REQUEST_TEMPLATE.md.

**Comment by rwwagner90** [comment]
@yowainwright I really don't think we need those things right now. Would be greatly preferential to get some bugs / feature PRs etc reviewed and merged, rather than adding more and more process.
