### ISSUE TITLE
Ember 3.0 - browser refresh causes back button to stop working

### ISSUE THREAD

**Issue by joshkg** [dollarshaveclub/ember-router-scroll#104]
After upgrading to ember v3.0, I've noticed that in a particular scenario the back button fails to produce a template render on the previous route. Steps to reproduce:

1. Open new tab in Chrome
2. navigate to initial application url (i.e. localhost:4000/search)
3. do a browser page refresh
4. transition to a new route (e.g. localhost:4000/results)
5. hit the browser back button

At this point, I see the previous route name in the URL bar (localhost:4000/search), however there is no actual application transition, no rendering of that route, nothing but a history state change in the URL bar.

I tried creating a new Ember app from scratch, tested this type of route transition without router-scroll, then installed router-scroll and tested again, and can confirm that the bug is only present with the addon install.

**Comment by willviles** [comment]
I'm experiencing the same issue. @joshkg have you found a fix?

**Comment by joshkg** [comment]
@willviles Nope, I've had to remove router-scroll, hopefully someone will find some time to dig in soon.

**Comment by joshkg** [comment]
Issue should be fixed with PR #130. @willviles give that a spin (you'll need to use master branch).
