### ISSUE TITLE
Consider moving mixin location

### ISSUE THREAD

**Issue by bcardarella** [dollarshaveclub/ember-router-scroll#11]
The README states you should use:

```js
import RouterScrollMixin from 'ember-router-scroll';
```

However the mixin is actually located elsewhere, so you have to do:

```js
import RouterScrollMixin from 'ember-router-scroll/mixins/router-scroll';
```

which is OK but the line in the README seems better. To achieve this you can move `ember-router-scroll/addon/mixins/router-scroll.js` to `ember-router-scroll/addon/index.js`

**Comment by briangonzalez** [comment]
@bcardarella Agreed.

@bennycwong Mind taking a stab?
