### ISSUE TITLE
[Feature] Implement CircleCI

### ISSUE THREAD

**Issue by yowainwright** [dollarshaveclub/ember-router-scroll#110]
## Implement CircleCI 

 For this issue CircleCi will/can be implemented. 

### Reasons 🤔

- support from the DSC team
- faster CI
- automate post-merge features

----

### Steps 📊

The checklist items will be in separate PRs for readability. 
Versioning for these PRs will try to best support the community.

-----

#### Key Items ✅

- [x] adds/update eslinting — re-adds [dsc rules again](https://github.com/dollarshaveclub/ember-router-scroll/commit/8d885440d6a6de71d6ccde830c8c6fdb30114a46). 
- [x] Init [CircleCi](https://circleci.com/)
- [x] Add [ES-Check](https://github.com/dollarshaveclub/es-check)
- [x] Remove Travis
- [ ] Init [CodeCov](https://codecov.io/gh)
- Add tests—not a checklist item, this is another issue.
- Add post-merge featuring—not a checklist item, this is another issue (This issue will be added closer to implementation time).
   - Publishing
   - Auto PR/merge changelog

**Comment by yowainwright** [comment]
- There has been a push back in regards to linting changes. Please provide links to technical documentation as to why ember-router-scroll's eslint config blocks or is very difficult to use. 
  - https://github.com/dollarshaveclub/ember-router-scroll/pull/108
- There has been push back in regards to recent versioning. Please provide links to technical documentation into how semver should be used moving forward. 
  - https://github.com/dollarshaveclub/ember-router-scroll/pull/109

~Thank you! 🙏

**Comment by rwwagner90** [comment]
@yowainwright are you asking us for documentation as to why we are pushing back against the changes? I'm a little unclear as to who your comment is directed at.

**Comment by yowainwright** [comment]
Yes—provide links to Ember standard documentation that there is a divergence from. 

Who is **we** in context of the comment above?

**Comment by rwwagner90** [comment]
@yowainwright ember-cli generates default stuff. If you just run an `ember init` you can see the default output. It uses travis and standard eslint rules specific to Ember. We've now removed all that and added more ESLint stuff as well, so not only do we not enforce the Ember stuff, we are forcing people to change their code drastically to be able to contribute here.

Which *we* are you referring to?

@snewcomer, @dfreeman, and I are the ones who expressed concerns about these divergences.

**Comment by snewcomer** [comment]
Ditto with Robert.  My biggest concerns are:

1.  Upgrading the project will produce a large diff with `ember init`.
2.  It could get frustrating for a new contributor; esp one that doesn't know to run `npm run eslint` to fix the semicolons they added at the end of the line.

For me, these aren't deal killers b/c I can work around it.  I just always like to keep the friction to a minimum for any contributor since this is a popular addon and lots of ppl use it in the community.

Regarding the versioning, if things are automatic, I don't necessarily mind.  Unless you gave Robert npm publish right of course.  When I have a problem, I always go to the changelog/releases and see where something broke, rolling back minor/major versions until something broke.  I usually don't rollback to patch releases, b/c I assume those are backwards compat bug fixes.  In this case, does the minor version always bump?

https://semver.org/

**Comment by rwwagner90** [comment]
A version is typically only bumped if something changed to consumers of the package. Otherwise, there is no need to release anything or change the version, just pushed to master.

**Comment by snewcomer** [comment]
Agreed!  In the setup with automatic npm publishing, is the minor version being bumped every time?  Or is this done manually?  I was assuming it was automatic based on reading PR comments but wasn't certain.

**Comment by yowainwright** [comment]
1. That's a great point @snewcomer! I forgot that when upgrading `ember init` is run. 
   - I would like to add a ember-addon.js file [here](https://github.com/dollarshaveclub/eslint-config-dollarshaveclub/)
  - or, use something like [this](https://www.npmjs.com/package/eslint-plugin-ember-addons)
  - the reason why I would prefer a config is that I can make a eslint update for ember addons is 1 place to support all of dsc's ember addons. 
2. I like to expect a eslint command for fixing eslint issues pre-push. 
  - Shound the command be renamed?
3. **Publishing rights:** that is discussion that is beyond/above me. That's why I've been trying to help as I can. In order for auto-publishing though—tests need to be stronger. ...So I'm trying to make CI uniform to DSC, then add tests, then add deployment support.

**Comment by yowainwright** [comment]
@snewcomer is order to avoid the `npm publish` every time, harmless changes could/would be used. 

I hope, as common language is developed, something that works for the people contributing right now can be implemented. I think it can. 😊

**Comment by snewcomer** [comment]
I see.  

2.  So the `pre-push` would tell the user to run this command?  So they aren't left wondering, "hey all I did was add one line (with a semi-colon, for example).  But linting, thus CI failed for some reason."

3. Forgive me if I am missing something.  So a PR is merged - Is the version bumped and published automatically?  Or is that done manually by someone with npm publish rights?

**Comment by yowainwright** [comment]
2. A contributor does not have to do any linting at all. However, linting may fail during CI. 
  - To see where a contributor is at in regards to eslint before pushing (pre-pushing), they can run `npm run eslint` and that command will fix most eslint issues. CI runs `npm run lint:js` which will not auto-fix eslint issues. 
3. We can/will configure `npm publish` based specific changes. So like, maybe we will not add new versions b/c of package updates or `.md` updates.

**Comment by rwwagner90** [comment]
I'm just still not sure what we gain from these changes. If DSC plans to be very involved in development of this and actively working on the bugs and features, then the linting is totally fine and valid, but if we want to community to continue to help out, I don't think we want it.

The same with not using Travis or moving away from anything Ember prescribes. If we stick to the standards, it's super easy for anyone to jump in, but if we add a bunch of hoops to jump through, people will just not help out.

**Comment by yowainwright** [comment]
@rwwagner90 will manage open issues. I am closing this pr. This issue will not be done.
