### ISSUE TITLE
Ember 3.1.x deprecation warning

### ISSUE THREAD

**Issue by willviles** [dollarshaveclub/ember-router-scroll#125]
`
DEPRECATION: Route#router is an intimate API that has been renamed to Route#_router. However you might want to consider using the router service [deprecation id: ember-routing.route-router]
`

The deprecation warning relates to [index.js#L35](https://github.com/dollarshaveclub/ember-router-scroll/blob/master/addon/index.js#L35). I believe it relates to `Route.router` [being renamed](https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-routing-route-router) to `Route._router` in Ember 3.x and recommended access of router properties now being through the router service.

**Comment by rwwagner90** [comment]
Actively being worked on in a PR https://github.com/dollarshaveclub/ember-router-scroll/pull/120

**Comment by bgentry** [comment]
Maybe this was intentional, but these fixes were not included in the v0.5.0 or v0.6.0 releases that were just put out.

**Comment by snewcomer** [comment]
@bgentry Yeah I think 0.6.0 is 13 commits behind.  We should release 0.7.0 to include those 13 commits.

**Comment by rwwagner90** [comment]
Yeah, those tags were pushed a long time after the actual releases were released. We need a new release with all the new changes. I still do not have permissions to npm though. @yowainwright can you please release? I assume it's still not an option to give me npm permissions?

**Comment by puwelous** [comment]
ping @yowainwright 🙏

**Comment by willviles** [comment]
Our project is still pinned to commit [a87ca1a](https://github.com/dollarshaveclub/ember-router-scroll/commit/a87ca1afd706540d904a7ab5ad66390944fab72c), so it'd be great to have a release @yowainwright 👋

**Comment by yowainwright** [comment]
👍 will review/release asap.

**Comment by rwwagner90** [comment]
0.7.0 was released, which should fix this. No need for another release, I don't think.

**Comment by snewcomer** [comment]
I think so too. We are using 0.7.0 and has been working great for us (w/ no dep warnings)!!

**Comment by willviles** [comment]
Sorry guys, the lack of a clear version bump commit threw me. Didn't notice the `0.7.0` release and it is working great. Awesome stuff 👍
