### ISSUE TITLE
Back button broken

### ISSUE THREAD

**Issue by rwwagner90** [dollarshaveclub/ember-router-scroll#136]
As of 0.7.0, if I visit the index route of my app, scroll, then visit another route, and try to hit the back button to go back, the url changes, but my transition to the other route does not happen.

**Comment by rwwagner90** [comment]
Never mind, false alarm!

**Comment by samselikoff** [comment]
@rwwagner90 I'm seeing this in a few apps as well... what was your fix?

**Comment by rwwagner90** [comment]
@samselikoff I was just linked to the wrong version with `yarn link` I believe. Installing 0.7.0 again fixed it for me.

**Comment by samselikoff** [comment]
Sweet 👍 Thanks!
