### ISSUE TITLE
scroll to top not working with module unification?

### ISSUE THREAD

**Issue by NullVoxPopuli** [dollarshaveclub/ember-router-scroll#142]
I have a bunch of things going on in this project, but this is my attempt to get ember-router-scroll working: https://github.com/NullVoxPopuli/emberclear/commit/589303bd9354f9cab069dcea95b73f5f486b1ab0

silly things I'm doing:
 - module unification
 - es classes (should only be relevant for routes?)
 - fastboot & prember

Anything obvious stand out?

**Comment by snewcomer** [comment]
@NullVoxPopuli Thx for the example!  Before digging in, what happens when you remove the `routerScroll` block in your environment file?  Also `delayScrollTop` is most likely something you don't want (have it in there for edge cases).

**Comment by NullVoxPopuli** [comment]
@snewcomer when I remove `routerScroll` from my environment file, I see the same behavior. the scroll position more or less doesn't change when I change routes. and thanks for the tip!

**Comment by NullVoxPopuli** [comment]
not yet. I'm currently blocked by some silly canary stuff. I've made a todo on the emberclear repo to investigate: https://gitlab.com/NullVoxPopuli/emberclear/issues/23

**Comment by NullVoxPopuli** [comment]
just tested -- still doesn't work. :-\
could it be that my scrolling container isn't always the body?

**Comment by yowainwright** [comment]
@NullVoxPopuli it definitely [could be](https://github.com/dollarshaveclub/ember-router-scroll/blob/master/addon/services/router-scroll.js#L13-L60). 😃

**Comment by NullVoxPopuli** [comment]
figured it out  -- here is the  diff

```diff
diff --git a/packages/frontend/config/environment.js b/packages/frontend/config/environment.js
index 603d924..f545eda 100644
--- a/packages/frontend/config/environment.js
+++ b/packages/frontend/config/environment.js
@@ -52,11 +52,9 @@ module.exports = function(environment) {
       },
     },
 
-    // routerScroll: {
-    //   scrollElement: 'body',
-    //   // targetElement: '#emberclear-topnav',
-    //   delayScrollTop: true,
-    // },
+    routerScroll: {
+      scrollElement: '[data-scroll-container]',
+    },
 
     APP: {
       // Here you can pass flags/options to your application instance
diff --git a/packages/frontend/src/ui/components/off-canvas-container/template.hbs b/packages/frontend/src/ui/components/off-canvas-container/template.hbs
index 8133436..41aa535 100644
--- a/packages/frontend/src/ui/components/off-canvas-container/template.hbs
+++ b/packages/frontend/src/ui/components/off-canvas-container/template.hbs
@@ -31,12 +31,14 @@
   {{/if}}
 
 
-  <div class='
-    flex-column flex-grow
-    is-fullheight overflows
-    {{if sidebar.isShown
-      "is-sidebar-visible"
-      "is-sidebar-hidden"}}'>
+  <div
+    data-scroll-container
+    class='
+      flex-column flex-grow
+      is-fullheight overflows
+      {{if sidebar.isShown
+        "is-sidebar-visible"
+        "is-sidebar-hidden"}}'>
 
     {{yield}}
 

```

it looks like delayScrollTop didn't work for my app, which is fine -- I don't need it:)

**Comment by yowainwright** [comment]
Thanks @NullVoxPopuli for the useful links and code snippet! 

I'm it will benefit others!!! 🙏

**Comment by NullVoxPopuli** [comment]
so, this is weird -- the above works in development, but not in production at https://emberclear.io/
the data-scroll-container attribute tag is still there. :-\

**Comment by yowainwright** [comment]
@NullVoxPopuli dammit. Looking. I will look more soon.

----

An aside, not to take away from frustration, I read your blog post [here](https://dev.to/nullvoxpopuli/the-emberjs-of-the-future-today-12c) = nice! 🎉

**Comment by NullVoxPopuli** [comment]
thanks!! <3

**Comment by NullVoxPopuli** [comment]
ok, I may have lied before, I have the following situation: 
![image](https://user-images.githubusercontent.com/199018/46768384-f668a480-ccb5-11e8-823d-4cf47935d005.png)

going from right to left:
- emberclear tab:
  - in the console, I can test that selecting the '#scrollContainer' and calling the `scrollTo`  correctly moves the viewport up
 - editor (bottom):
   - router: hopefully configured correctly
   - environment: ENV.routerScroll.scrollElement = '#scrollContainer';
   - template: div has id 'scrollContainer'

I think the reason why I've psyched myself out with this is because the two pages I test this with have very different heights. So, I've squished my viewport to super short.
scrolling down to the footer like this on the home screen:

![image](https://user-images.githubusercontent.com/199018/46768510-6b3bde80-ccb6-11e8-9e5b-dffa509f820f.png)

and then clicking FAQ:
![image](https://user-images.githubusercontent.com/199018/46768523-74c54680-ccb6-11e8-9c85-05980f38580c.png)

no scroll happened. :-\

This _has_ to be something obvious, yeah?

**Comment by NullVoxPopuli** [comment]
I am legit confused now. it's working locally on a different computer :-\

**Comment by NullVoxPopuli** [comment]
I have passing tests! :)

![image](https://user-images.githubusercontent.com/199018/46799121-e9819a80-cd21-11e8-9dfd-130e5dd2a29e.png)

(I was inspired by ember-router-scroll's tests)

**Comment by NullVoxPopuli** [comment]
though, is there a better way to manage viewport size than to hack at the style attribute?
