### ISSUE TITLE
Corber support?

### ISSUE THREAD

**Issue by lougreenwood** [dollarshaveclub/ember-router-scroll#152]
Corber (formerly Ember Cordova) requires that the application uses the `'hash'` `locationType`.

When I use `hash` with the add-on it appears to work, except for a noticeable stutter just before the new route loads (although I don't notice this stutter on desktop - possibly because of more CPU)

Can you envisage it being possible to create some `router-scroll-hash` locationType which extends hash instead of history?

**Comment by yowainwright** [comment]
@lougreenwood sorry for taking so long to respond. 

Would you be interested in submitting a PR?

**Comment by yowainwright** [comment]
Have you tried making the change within your app?...by updating the ember-router-scroll within your node_modules and building? 

Also, in your comment: 
> When I use hash with the add-on it appears to work, except for a noticeable stutter just before the new route loads (although I don't notice this stutter on desktop - possibly because of more CPU)
Are you specifying an issue you're seeing on mobile?

**Comment by lougreenwood** [comment]
Yeah, sorry - I don't mean how to edit an add-on - more the technicalities of the router system, and why a new location type was needed etc so I could try building something similar for `hash` location type.

But no worries, if nothing comes to mind for you I'll try to figure it out if I start on the PR 😄

Re the mobile issue - yeah, I think there may be an issue, but only when using the wrong location type (`hash` instead of `routerscroll` in a Cordova environment) - which is to be expected since the it's not following the instructions.

**Comment by yowainwright** [comment]
Yes, I was misunderstanding you. 😀 Sorry about that. 

The steps to provide hash functionality are:

- copy `router-scroll.js` in `addon/locations` and `app/locations`
- create the necessary functionality for `HashLocation`
- update the stateUuid in `addon/services`
- add tests
- provide readme updates of the optional functionality
