### ISSUE TITLE
Change timing of window.scrollTo

### ISSUE THREAD

**Issue by bcardarella** [dollarshaveclub/ember-router-scroll#17]
Currently `window.scrollTo` is fired in `didTransition` which itself is wrapped in an Ember.runloop call. And the transition is fired from within the runloop. The result is that there is a jitter when scrolling to a different position. The page renders and there is a noticeable jump. It is fast but noticeable.

I believe the scroll positioning should be done elsewhere. It would be great if we could hook into an afterRender callback. Not sure if one is fired for the entire page.

**Comment by joshkg** [comment]
@bcardarella Should we consider this issue closed after #101?

**Comment by bcardarella** [comment]
:+1:
