### ISSUE TITLE
registerWaiter

### ISSUE THREAD

**Issue by gordonbisnor** [dollarshaveclub/ember-router-scroll#176]
I had this addon working in my application until I ran ember-cli-update.

I am now getting this error *in production only*:

jQuery.Deferred exception: Cannot read property 'registerWaiter' of undefined TypeError: Cannot read property 'registerWaiter' of undefined

ember-source version 3.5.1

**Comment by snewcomer** [comment]
So this is probably coming from https://github.com/ember-app-scheduler/ember-app-scheduler

Curious: do you have this configuration set?  I don't (I don't want to opt into `ember-app-scheduler` since I don't need to delay scroll top functionality) and haven't seen this error on 3.5.1.

```
ENV['routerScroll'] = {
  delayScrollTop: true
};
```

**Comment by gordonbisnor** [comment]
@snewcomer No I don't have delayScrollTop set at all.

**Comment by gordonbisnor** [comment]
@snewcomer Thanks for the tip, I think my issue was related to this one: https://github.com/ember-app-scheduler/ember-app-scheduler/issues/69 – I tried removing yarn.lock and yarning again and it now seems to be working just fine!
