### ISSUE TITLE
`handlerInfo.handler` is deprecated

### ISSUE THREAD

**Issue by AndriesDemeulenaere** [dollarshaveclub/ember-router-scroll#186]
`handlerInfo.handler` is deprecated. It has been renamed to RouteInfo to align with the [new router service RFC](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md).

See:
https://emberjs.com/deprecations/v3.x#toc_remove-handler-infos

**Comment by snewcomer** [comment]
@AndriesDemeulenaere Thx for the issue!  This is fixed in master.  Awaiting a new `1.1.0` release!

https://github.com/dollarshaveclub/ember-router-scroll/commits/master
https://github.com/dollarshaveclub/ember-router-scroll/pull/187

**Comment by williamweckl** [comment]
@snewcomer any expectations of a release date for the next version?

By the way, thanks for the amazing job done! :)

**Comment by mehulkar** [comment]
hello :) any updates on getting this new version out there?

**Comment by snewcomer** [comment]
1.1.0 was released!  Thank you everybody!

https://www.npmjs.com/package/ember-router-scroll
