### ISSUE TITLE
1.3.0, 1.3.1 releases are incompatible with Ember Fastboot

### ISSUE THREAD

**Issue by jordanbyron** [dollarshaveclub/ember-router-scroll#220]
Looks like changes made in #217 and released as 1.3.0 reference `document` which effectively breaks this library for projects also using ember fastboot. 

```
ReferenceError: document is not defined
    at getScrollBarWidth (/var/folders/pw/kjxgyxss2wz0kj8lmfnd_vdm0000gn/T/broccoli-41877Iv5L0goPohmi/out-454-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-router-scroll/utils/scrollbar-width.js:11:1
```

**Comment by jordanbyron** [comment]
@snewcomer it does not. There are still [two references to document](https://github.com/DockYard/ember-router-scroll/blob/master/addon/index.js#L10-L11) at the top of `addon/index.js`

**Comment by snewcomer** [comment]
🤦‍♂ 1.3.2?

**Comment by jordanbyron** [comment]
@snewcomer that seems to have restored Fastboot compatibility on our project. Thanks for the quick turn around.
