### ISSUE TITLE
Use Circle to publish 🚀

### ISSUE THREAD

**Issue by arjansingh** [dollarshaveclub/ember-router-scroll#26]
https://docs.travis-ci.com/user/deployment/npm
https://github.com/npm/node-semver

**Comment by rwwagner90** [comment]
@arjansingh I used travis before to build, push the dist to github, tag, and release to bower and npm. Would be happy to help if you need it. You can reference my config as well https://github.com/jibeinc/juice/blob/master/.travis.yml

**Comment by briangonzalez** [comment]
@rwwagner90 We'd love your help here. Let me know.

**Comment by rwwagner90** [comment]
@briangonzalez is this still being worked on? I thought I remembered it was going to be merged into Ember itself at some point?

**Comment by briangonzalez** [comment]
It is :)

**Comment by rwwagner90** [comment]
@briangonzalez would you mind adding me as a collaborator here and assigning the issue to me, so I don't lose track of it? I would love to help, but don't have the free time right this second.

**Comment by rwwagner90** [comment]
Thanks!

**Comment by yowainwright** [comment]
Publishing can be added if/when we switch to CircleCi. 😁
