### ISSUE TITLE
Uncaught Error: Could not find module `ember-getowner-polyfill`...

### ISSUE THREAD

**Issue by Mithrilhall** [dollarshaveclub/ember-router-scroll#34]
I get the following error after installing and making it to Step 5: Profit:

> Could not find module `ember-getowner-polyfill` imported from `ember-router-scroll/index`

Once I manually installed `ember-getowner-polyfill` it worked fine.

**Comment by arjansingh** [comment]
https://github.com/dollarshaveclub/ember-router-scroll/blob/master/package.json#L75 << this should be in `dependencies` and not `devDependencies`. Would you mind creating a PR for that?

**Comment by krasnoukhov** [comment]
This seems to be fixed on master
