### ISSUE TITLE
Mimic back/forward behavior on normal transitions

### ISSUE THREAD

**Issue by billdami** [dollarshaveclub/ember-router-scroll#48]
Does the addon support a way to return the user to the saved scroll position for a previous page without having to be invoked by a "Back/Forward" browser event, i.e. via clicking a `{{link-to}}` that sends the user back to that previous page?

The scenario is a common master list/detail view case, where the user scrolls through a list of items, selects one to navigate to a detail view, the clicks a "Back to list" link, which I would like to return the user to their previous scroll position in the list, like what happens if they click the browser Back button. Currently, this returns them back to the top of the list.

If the addon does not support this, is there viable way to extend it to do so, or a recommended path to achieving this outside outside of ember-router-scroll altogether?

**Comment by briangonzalez** [comment]
@billdami  Thanks for your question.

You can achieve this by creating an event in your component which simply does the following:

```js
Ember.component.extend({
  tagName: 'a',
  actions: {
    onClick() {
      window.history.back();
    }
  }
});
```
