### ISSUE TITLE
Is this addon still needed in Ember 2.13?

### ISSUE THREAD

**Issue by myartsev** [dollarshaveclub/ember-router-scroll#54]
I got thrown off by the note in the readme for this project and my experience with using this addon in Ember 2.13.

[RFC #186](https://github.com/emberjs/rfcs/pull/186) has made it into Ember 2.13 but the scroll behaviour I was looking is only there if I use this add-on. Am I missing something to enable the scrolling behaviour in Ember core?

**Comment by ktrhn** [comment]
I am asking myself the same question. Seems it is in ember, but need to be enabled somehow. How?

**Comment by maxwerr** [comment]
[x-posted in ember core](https://github.com/emberjs/ember.js/issues/15324)

**Comment by rwjblue** [comment]
Yes, this addon is still needed. The RFC to Ember simply made this addons job a tad bit easier (and allowed it to rely on only public APIs). Specifically, I believe that step 3 in the [usage instructions on the README](https://github.com/dollarshaveclub/ember-router-scroll#usage) is no longer needed with Ember 2.13.

@bcardarella and/or @briangonzalez can y'all confirm?

**Comment by bcardarella** [comment]
The Location can be deprecated but the Service is still necesarry

**Comment by bcardarella** [comment]
and the router mixin is still necessary

**Comment by maxwerr** [comment]
Using version 0.2.0 and ember 2.13.3, I can't get this working at all yet.

I ember install'ed, Router mixin'ed, and (progressively, to test) added the two environment.js lines. To no avail, not sure if I'm just missing something--will try to post example repo later if I can't sort it out.

**Comment by bcardarella** [comment]
@rwjblue I believe 2.14 is when the feature flag drops. It is still there for 2.13: https://github.com/emberjs/ember.js/blob/v2.13.3/packages/ember-routing/lib/location/history_location.js#L19

**Comment by maxwerr** [comment]
That makes sense, I got thrown by the "until released in 2.13" bit.  But referring to `ember-source`, I can't use the feature flags, but when I bump to `"ember-source": "^2.14.0-beta.3"`, I'm still not getting any results. Do the story/instructions change in 2.14?

**Comment by bcardarella** [comment]
The only difference that should be necessary in 2.14 will be not having to change your location type in `config/environment.js`

**Comment by maxwerr** [comment]
Gotcha. Still nada when I go back to `auto`, but I'm gonna assume I have some environmental issue going on and try this on a new app before I continue to pester here.

**Comment by rwjblue** [comment]
@bcardarella - I didn't strip the conditional in the source until later, but the feature is enabled in 2.13.  

![screenshot](https://monosnap.com/file/WspMIy156zeREIEwhGEAt0DmuNBzXL.png)

**Comment by bcardarella** [comment]
Re: @maxwerr's issue. I just SH'd with him and there appears to be something else at play. The `window.scrollY` value never changes. I suspect the scrolling is within a container div with an overflow allowed and not changing the actual window height. This won't work with ember-router-scroll

**Comment by bcardarella** [comment]
I recommended https://github.com/ef4/memory-scroll

**Comment by briangonzalez** [comment]
@bcardarella @rwjblue 

If I understand correctly, this repo should be fixed up with?

- [ ] Keep service and mixin
- [ ] Remove location
- [ ] Major version bump
- [ ] Fix tests

**Comment by bcardarella** [comment]
@briangonzalez I would recommend a deprecation in the location for the time being that detects the Ember version. >= 2.13 display deprecation that recommends keeping the location as `auto` or `history`. This way upgrades won't break.

**Comment by bcardarella** [comment]
Post major version bump location can be dropped

**Comment by briangonzalez** [comment]
Thoughts on publishing them in tandem? This addon is currently at 0.2.0

- `0.2.0` -> `0.3.0` deprecate warning for location
- `0.2.0` -> `1.0.0` location removed

**Comment by bcardarella** [comment]
Seems good to me!
