### ISSUE TITLE
Attempting to inject an unknown injection: 'service:scheduler'

### ISSUE THREAD

**Issue by kpfefferle** [dollarshaveclub/ember-router-scroll#66]
When running tests on a project using `ember@2.14.1` and `ember-cli@2.14.2`, all of my tests blow up with the following error:

```
Assertion Failed: Attempting to inject an unknown injection: 'service:scheduler'
```

**Comment by kpfefferle** [comment]
Silly me, I just needed to add `'service:scheduler'` to the `needs` of our Controller unit tests!

**Comment by briangonzalez** [comment]
@kpfefferle 👍
