### ISSUE TITLE
safari resets scroll position

### ISSUE THREAD

**Issue by cecemel** [dollarshaveclub/ember-router-scroll#70]
Hi, 

the plugin is working fine on firefox and chrome, unfortunately it is not working on safari (10.1.1) also on safari mobile (sorry unknown version). 
Using ember 2.14, and ember-router-scroll 0.1.1.

Any ideas?
thanks!

**Comment by rwwagner90** [comment]
Hi @cecemel have you tried the latest version of ember-router-scroll? It appears 0.3.0 is the latest.

**Comment by cecemel** [comment]
Hi, 

thanks for reply. Unfortunately issue remains. I can point you to my website in dev modus, so you can have look at it yourself, but I'd prefer to do this in a private message.

**Comment by briangonzalez** [comment]
@cecemel – Go ahead and pop me an email: brian@dollarshaveclub.com

**Comment by cecemel** [comment]
Hi there, 

any updates on the issue?

thx

**Comment by rwwagner90** [comment]
@cecemel did you send an email to @briangonzalez?

**Comment by briangonzalez** [comment]
He did send it to me, I have just been a bum. I'll check it out tomorrow!

**Comment by yowainwright** [comment]
@cecemel did your issue get resolved? If so, what was the fix?! 😊

**Comment by ajcolter** [comment]
Also seeing this issue on mobile Safari with `"ember-router-scroll": "^0.4.0",` in my package.json. Has a fix been released?

**Comment by rwwagner90** [comment]
@briangonzalez does not work for DSC anymore. You'll want to direct your questions at @yowainwright .

**Comment by yowainwright** [comment]
Reviewed on safari with a modern iphone and ember-router-scroll is working as expected with version `1.0.0`.
