### ISSUE TITLE
Getting error "Cannot read property 'afterContentPaint' of null" when running tests

### ISSUE THREAD

**Issue by nrcjbarry** [dollarshaveclub/ember-router-scroll#72]
Occasionally on our build server, I get a failing test with the following error: `Cannot read property 'afterContentPaint' of null`

There are only 2 hits on Google for `afterContentPaint`, and one of them is this issue: https://github.com/sreedhar7/ember-app-scheduler/issues/9

This addon seems to be the only thing using that library. Have you ran into this error while using `ember-router-scroll`?

**Comment by briangonzalez** [comment]
@cclo7 Any ideas?

**Comment by nrcjbarry** [comment]
I am using headless Chrome to run my tests with this `testem.js` config:

```js
module.exports = {
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  launch_in_ci: [
    'Chrome'
  ],
  launch_in_dev: [
  ],
  browser_args: {
    Chrome: [
      '--disable-gpu',
      '--headless',
      '--remote-debugging-port=9222',
      '--window-size=1440,900'
    ]
  }
};
```

**Comment by cclo7** [comment]
@nrcjbarry what type of tests are you running when encountering this error? Acceptance, integration, or unit test?

**Comment by nrcjbarry** [comment]
@cclo7 I have only seen it happen in acceptance tests.

**Comment by kpfefferle** [comment]
I too am getting this during (some) acceptance tests

**Comment by nrcjbarry** [comment]
I also get this on my local machine too both when running `ember test` and `ember test --server`. I'm using Ember 2.15 and Ember CLI 2.15.1.

Here is a screen shot of the stack trace on one of them:

![screen shot 2017-09-12 at 12 18 42 pm](https://user-images.githubusercontent.com/29584131/30651929-0c085c4a-9df5-11e7-9ea8-7bcdd812e296.png)

**Comment by YoranBrondsema** [comment]
I encountered the same issue after an upgrade to Ember.js 2.15. I dug a bit deeper into it and I may have found out the cause. I don't think the error is in `ember-router-scroll` but rather in `ember-app-scheduler`.

I provide more explanation here: https://github.com/sreedhar7/ember-app-scheduler/issues/11.

**Comment by YoranBrondsema** [comment]
Nevermind, I got it wrong... I figured out later that this addon uses an old version of `ember-app-scheduler`. PR #73 updates it to the latest version and that fixed the problem for me.

**Comment by ryanto** [comment]
I'm still getting this error in my application's acceptance tests. Wondering if 0.2.0 fixed it for everyone else?

**Comment by rwwagner90** [comment]
@ryanto do you mean 0.4.0? That is the latest release.

**Comment by nrcjbarry** [comment]
@ryanto it was fixed for me for months up until I upgraded to Ember 3.0 last week. I started seeing this error again only on one test (the same test) every time. I fixed it by deleting my `package-lock.json` file and doing another `npm install`. I haven't seen it in the last 2 days.

**Comment by ryanto** [comment]
I'm running master, but this could be something I'm doing in my app. Just wanted to ask.

**Comment by snewcomer** [comment]
I haven't seen this error in a month or so (which before saw quite often in our CI build).  Note we are on cli@3.0 and 0.5.0 for `ember-router-scroll` @ryanto

**Comment by bantic** [comment]
I'm still seeing this error as well, fairly sporadically in acceptance tests. Using ember-router-scroll 0.5.0 and ember-app-scheduler 0.2.1. Still looking into why, but I'm curious if anyone else is still getting it, or has a suggestion for a fix.

**Comment by snewcomer** [comment]
@bantic I think it is 👇.  It's close to being done...made a PR to get the tests passing and have been awaiting feedback.  Maybe I should push to his master instead 🤔 

https://github.com/sreedhar7/ember-app-scheduler/pull/15

**Comment by ryanto** [comment]
Still seeing this. From following development on ember-app-scheduler it looks like this PR could maybe be a fix.

https://github.com/dollarshaveclub/ember-router-scroll/pull/129

**Comment by snewcomer** [comment]
@samselikoff @ryanto What version are you guys on?  Still master?  I perhaps would have thought the PR to make app-scheduler optional would have fixed it.  I would imagine your code is never calling `scheduleWork`, right?

https://github.com/dollarshaveclub/ember-router-scroll/blob/master/addon/index.js#L32

**Comment by ryanto** [comment]
Ah thanks for pointing that out! I didn't realize this was an option... Let me give it a try.

**Comment by rtablada** [comment]
@snewcomer/@ryanto heads up the issue actually seems to lie in the `flushQueue` from Ember App Scheduler which runs even though router-scroll isn't directly using it. Since the service is still injected and initialized these lifecycles are still happening.

I have made a PR https://github.com/ember-app-scheduler/ember-app-scheduler/pull/45 to address this and check for service lifecycles.

**Comment by rtablada** [comment]
I'm not sure how `ember-app-scheduler` will handle porting back to version 2.* as listed as a dependency for `ember-router-scroll`.

**Comment by snewcomer** [comment]
@ryanto @bantic Whenever you have a chance, mind giving this branch a spin?  I tried it and seems to work great.  Just probably need another approval and we can merge and release a new version!

https://github.com/dollarshaveclub/ember-router-scroll/pull/139
