### ISSUE TITLE
Can we use the 'history' type for url type?

### ISSUE THREAD

**Issue by Matthijsy** [dollarshaveclub/ember-router-scroll#82]
It looks like that when setting the `locationType` to `router-scroll` it will behave like [hash](https://guides.emberjs.com/v2.15.0/configuring-ember/specifying-url-type/#toc_hash). The project I am working on we use the [history](https://guides.emberjs.com/v2.15.0/configuring-ember/specifying-url-type/#toc_hash) type. Do I configure something wrong or is this the intended behavior of the addon?

**Comment by briangonzalez** [comment]
I see that we're extending `HistoryLocation` [here](https://github.com/dollarshaveclub/ember-router-scroll/blob/master/addon/locations/router-scroll.js#L11).

**Comment by briangonzalez** [comment]
If you have an example app, I can take a look.

**Comment by Matthijsy** [comment]
After a bit more testing I found out that I forgot to enable the `historySupportMiddleware`, so it is working with the history type.
