### ISSUE TITLE
Add support for navigating to a "#" (hash) url.

### ISSUE THREAD

**Issue by robert-j-webb** [dollarshaveclub/ember-router-scroll#83]
Hi!

If I have a link like:
`example.com/hash#hashId`

It would be nice if the app would properly navigate to it. I can think of a really quick and dirty fix for it in this function:

https://github.com/dollarshaveclub/ember-router-scroll/blob/2d577cd4a695310e02db1217d9f8eff5f9bdf1d1/addon/index.js#L30

```js
  updateScrollPosition(transitions) {
    const lastTransition = transitions[transitions.length - 1];
    const url = lastTransition.handler.get('router.currentURL');
    
    let scrollPosition;
    if(url.includes("#")) {
      const hashElement = document.getElementById(url.split("#").pop());
      scrollPosition = { x: hashElement.offsetLeft, y: hashElement.offsetTop }
    } else {
      scrollPosition = get(this, 'service.position');
    }
    ... Rest of the code here ...
  }
```

Let me know if this is something you would like or alternatively, that I'm completely wrong and you do in fact support # links.

**Comment by robert-j-webb** [comment]
I forked this and wrote a patch for it. I haven't written any tests but I will as soon as I know that you'd like the PR. I work for Nest and we are more than happy to contribute to this project.

**Comment by rwwagner90** [comment]
Hi @robert-j-webb I don't see why we wouldn't want to support both url types. I would accept a PR, but I'm probably not who would have final say on this.

**Comment by robert-j-webb** [comment]
Ok I'll write one up.

**Comment by robert-j-webb** [comment]
Ok, @briangonzalez, @rwwagner90, The PR is ready.
