### ISSUE TITLE
Will not work with FastBoot

### ISSUE THREAD

**Issue by mminkoff** [dollarshaveclub/ember-router-scroll#85]
pull request on the way!

**Comment by rwwagner90** [comment]
@mminkoff when you say it does not work with fastboot, you mean if you run only in fastboot? It doesn't seem to cause any errors for me, but I was doing fastboot for initial boot and letting the browser take over.

Do you have a reproducible case?

**Comment by ryanto** [comment]
Looks like this is causing a failure in fastboot: https://github.com/dollarshaveclub/ember-router-scroll/blob/master/addon/services/router-scroll.js#L28-L29

**Comment by ryanto** [comment]
Fixed in https://github.com/dollarshaveclub/ember-router-scroll/pull/92

**Comment by rwwagner90** [comment]
Thanks @ryanto!
