### ISSUE TITLE
Broken builds with 0.5 release

### ISSUE THREAD

**Issue by jeffjewiss** [dollarshaveclub/ember-router-scroll#87]
Hi there, I upgraded an addon using this as a dependency from router-scroll v0.4 to v0.5 and I'm seeing broken builds across a number of versions of Node and Ember.

You can see them here: https://travis-ci.org/jeffjewiss/ember-cli-postcss/builds/337610492

I downgraded to v0.4 and the builds are passing again: https://travis-ci.org/jeffjewiss/ember-cli-postcss/builds/337628529

I'll need to look into this further, but it may be related to #85

**Comment by briangonzalez** [comment]
@jeffjewiss If you could help dig in, that would be _greatly_ appreciated.

**Comment by jeffjewiss** [comment]
@briangonzalez yeah, I should be able to take a look this week. I'll try building with the Fastboot PR first, and then go from there. I have a few things I need to finish up first.

Cheers
