### ISSUE TITLE
Error when navigating to url with nothing after anchor #

### ISSUE THREAD

**Issue by TerminalStar** [dollarshaveclub/ember-router-scroll#88]
We're seeing a `Cannot read property 'offsetLeft' of null` error when navigating to a url with a trailing hash (e.g. http://example.com/home#). 

Looks to me like the culprit is this line here https://github.com/dollarshaveclub/ember-router-scroll/blob/master/addon/index.js#L38, as we're hitting that `if` condition even though there's nothing to be assigned to `hashElement`.

**Comment by rwwagner90** [comment]
@TerminalStar is this no longer an issue?

**Comment by TerminalStar** [comment]
Oops, no it is still a problem - accidentally closed via a pr 😅 

said pr introduced a fork with a quick fix into our project, i can add a test and open a PR here if you want?

**Comment by rwwagner90** [comment]
@TerminalStar that would be great!

**Comment by TerminalStar** [comment]
@rwwagner90 done! https://github.com/dollarshaveclub/ember-router-scroll/pull/90
