### ISSUE TITLE
Feature Discussion: targetElement to scroll to

### ISSUE THREAD

**Issue by snewcomer** [dollarshaveclub/ember-router-scroll#99]
For non `scrollElement` configs, It would be great to scroll to a y coordinate that is not window (y: 0).  Perhaps a config called `targetElement` and `window.scrollTo(x,y)` would take the x & y coordinates from the `targetElement.offsetTop`.

Also, the reason why `scrollElement` does not work is that the target element may not be scrollable, thus it's content not generating a scrollbar (and it's scrollTop == 0 all the time).

I can submit a PR if this sounds good to everybody!

**Comment by rwwagner90** [comment]
@snewcomer this sounds logical to me. Would be great to get some input from some of the other collaborators though. @briangonzalez any thoughts?

**Comment by snewcomer** [comment]
I'll start working on this now...
